### ISSUE TITLE
How do you get/set an object reference during collision callbacks?

### ISSUE THREAD

**Issue by airbrett** [stetre/moonchipmunk#3]
I am writing a collision handler but I am having trouble finding a way to get my game object from a body during say begin or pre-solve. I was expecting to find something like cpBodySetUserData/cpBodyGetUserData. How is this accomplished? Thanks for the great project.

**Comment by stetre** [comment]
Hi, sorry for the late response (I've been offline, yesterday).

When I write bindings for libraries such as this one, which often provide means to associate unspecified 'user data' to objects, I usually don't expose this capability to the user. There are two reasons for this choice:

The first is that at times such a capability turns out to be useful (if not essential) to the binding code, especially when callbacks are involved. This is not the case for the body object here, but having bound a few libraries I've learned from experience that it's safer to reserve this capability to the binding code, just in case.

The second reason is that this feature is not really needed in Lua because Lua has tables. Tables allow you to use values of any type as indices, so the functionality provided by get/set_user_data, when needed, is trivially implemented with a simple table indexed by the objects themselves. For example, in your case you would do something like this:

```
game_objects = {} -- map from body to game object

go1 = create_game_object(...)
b1 = cp.body_new(...)
game_objects[b1] = go1 -- this is set_user_data

go2 = create_game_object(...)
b2 = cp.body_new(...)
game_objects[b2] = go2
-- ...
-- ...
-- ...
-- given a body b, you can then retrieve the associated game object by just indexing the table
go = game_objects[b] -- this is get_user_data
```

Beside being likely faster than bindings, one nice thing of this approach is that you can use it also when libraries lack native ways to set and get user data associated to objects.

Thank you for the appreciation.

**Comment by airbrett** [comment]
Thanks, this worked for me.
